### ISSUE TITLE
add biomedicus to dependency

### ISSUE THREAD

**Issue by ymnliu** [nlpie/nlp-adapt-kube#4]
https://github.com/nlpie/nlp-adapt-kube/blob/b2a41016f921bb0e2dcfd41ee403992c6849a2e4/docker/biomedicus/Dockerfile#L7

It is trying to find the biomedicus release from the directory. Should the directory be configured before build?

**Comment by GregSilverman** [comment]
Yes, you need to download the build directory as per the directions from the wiki for biomedicus: https://github.com/nlpie/biomedicus/wiki/Installation you will also need to grab the models as listed on the wiki.
